// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcpchain/toolregistry/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryServerByIdRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryServerByIdRequest) Reset()         { *m = QueryServerByIdRequest{} }
func (m *QueryServerByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryServerByIdRequest) ProtoMessage()    {}
func (*QueryServerByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{2}
}
func (m *QueryServerByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryServerByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryServerByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryServerByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryServerByIdRequest.Merge(m, src)
}
func (m *QueryServerByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryServerByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryServerByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryServerByIdRequest proto.InternalMessageInfo

func (m *QueryServerByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryServerByIdResponse struct {
	Server *RegisteredServer `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (m *QueryServerByIdResponse) Reset()         { *m = QueryServerByIdResponse{} }
func (m *QueryServerByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryServerByIdResponse) ProtoMessage()    {}
func (*QueryServerByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{3}
}
func (m *QueryServerByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryServerByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryServerByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryServerByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryServerByIdResponse.Merge(m, src)
}
func (m *QueryServerByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryServerByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryServerByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryServerByIdResponse proto.InternalMessageInfo

func (m *QueryServerByIdResponse) GetServer() *RegisteredServer {
	if m != nil {
		return m.Server
	}
	return nil
}

type QueryServersByOwnerRequest struct {
	OwnerAddress string `protobuf:"bytes,1,opt,name=ownerAddress,proto3" json:"ownerAddress,omitempty"`
}

func (m *QueryServersByOwnerRequest) Reset()         { *m = QueryServersByOwnerRequest{} }
func (m *QueryServersByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryServersByOwnerRequest) ProtoMessage()    {}
func (*QueryServersByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{4}
}
func (m *QueryServersByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryServersByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryServersByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryServersByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryServersByOwnerRequest.Merge(m, src)
}
func (m *QueryServersByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryServersByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryServersByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryServersByOwnerRequest proto.InternalMessageInfo

func (m *QueryServersByOwnerRequest) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

type QueryServersByOwnerResponse struct {
	Servers []*RegisteredServer `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (m *QueryServersByOwnerResponse) Reset()         { *m = QueryServersByOwnerResponse{} }
func (m *QueryServersByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryServersByOwnerResponse) ProtoMessage()    {}
func (*QueryServersByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{5}
}
func (m *QueryServersByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryServersByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryServersByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryServersByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryServersByOwnerResponse.Merge(m, src)
}
func (m *QueryServersByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryServersByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryServersByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryServersByOwnerResponse proto.InternalMessageInfo

func (m *QueryServersByOwnerResponse) GetServers() []*RegisteredServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

type QueryAllServersRequest struct {
}

func (m *QueryAllServersRequest) Reset()         { *m = QueryAllServersRequest{} }
func (m *QueryAllServersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllServersRequest) ProtoMessage()    {}
func (*QueryAllServersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{6}
}
func (m *QueryAllServersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllServersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllServersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllServersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllServersRequest.Merge(m, src)
}
func (m *QueryAllServersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllServersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllServersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllServersRequest proto.InternalMessageInfo

type QueryAllServersResponse struct {
	Servers []*RegisteredServer `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (m *QueryAllServersResponse) Reset()         { *m = QueryAllServersResponse{} }
func (m *QueryAllServersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllServersResponse) ProtoMessage()    {}
func (*QueryAllServersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_762895bd348ec913, []int{7}
}
func (m *QueryAllServersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllServersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllServersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllServersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllServersResponse.Merge(m, src)
}
func (m *QueryAllServersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllServersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllServersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllServersResponse proto.InternalMessageInfo

func (m *QueryAllServersResponse) GetServers() []*RegisteredServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mcpchain.toolregistry.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mcpchain.toolregistry.QueryParamsResponse")
	proto.RegisterType((*QueryServerByIdRequest)(nil), "mcpchain.toolregistry.QueryServerByIdRequest")
	proto.RegisterType((*QueryServerByIdResponse)(nil), "mcpchain.toolregistry.QueryServerByIdResponse")
	proto.RegisterType((*QueryServersByOwnerRequest)(nil), "mcpchain.toolregistry.QueryServersByOwnerRequest")
	proto.RegisterType((*QueryServersByOwnerResponse)(nil), "mcpchain.toolregistry.QueryServersByOwnerResponse")
	proto.RegisterType((*QueryAllServersRequest)(nil), "mcpchain.toolregistry.QueryAllServersRequest")
	proto.RegisterType((*QueryAllServersResponse)(nil), "mcpchain.toolregistry.QueryAllServersResponse")
}

func init() { proto.RegisterFile("mcpchain/toolregistry/query.proto", fileDescriptor_762895bd348ec913) }

var fileDescriptor_762895bd348ec913 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0x33, 0xd1, 0x46, 0x3a, 0x4a, 0xc1, 0xb1, 0x6a, 0x59, 0xcd, 0x56, 0x07, 0xc5, 0x18,
	0x68, 0xc6, 0x44, 0x50, 0x4f, 0xda, 0xe4, 0xe6, 0x49, 0x5d, 0x0f, 0x42, 0x11, 0xe2, 0x24, 0x3b,
	0xac, 0x03, 0x9b, 0x9d, 0xed, 0xcc, 0xb6, 0xba, 0x94, 0x5e, 0x44, 0x3c, 0x0b, 0x1e, 0x3c, 0x79,
	0xf7, 0xe8, 0xcd, 0x7f, 0xa1, 0xc7, 0x82, 0x17, 0x4f, 0x22, 0x89, 0xe0, 0xbf, 0x21, 0x99, 0x99,
	0x6d, 0x13, 0x37, 0x59, 0x5b, 0xf0, 0x12, 0x26, 0xb3, 0xdf, 0x7b, 0xdf, 0x6f, 0xde, 0x7c, 0x0c,
	0xbc, 0x3a, 0xe8, 0xc7, 0xfd, 0x97, 0x94, 0x47, 0x24, 0x11, 0x22, 0x94, 0x2c, 0xe0, 0x2a, 0x91,
	0x29, 0xd9, 0xdc, 0x62, 0x32, 0x6d, 0xc4, 0x52, 0x24, 0x02, 0x9d, 0xcf, 0x24, 0x8d, 0x49, 0x89,
	0x73, 0x96, 0x0e, 0x78, 0x24, 0x88, 0xfe, 0x35, 0x4a, 0x67, 0x39, 0x10, 0x81, 0xd0, 0x4b, 0x32,
	0x5e, 0xd9, 0xdd, 0xcb, 0x81, 0x10, 0x41, 0xc8, 0x08, 0x8d, 0x39, 0xa1, 0x51, 0x24, 0x12, 0x9a,
	0x70, 0x11, 0x29, 0xfb, 0xb5, 0xde, 0x17, 0x6a, 0x20, 0x14, 0xe9, 0x51, 0xc5, 0x8c, 0x2d, 0xd9,
	0x6e, 0xf6, 0x58, 0x42, 0x9b, 0x24, 0xa6, 0x01, 0x8f, 0xb4, 0xd8, 0x6a, 0xf1, 0x6c, 0xd8, 0x98,
	0x4a, 0x3a, 0xc8, 0xfa, 0xad, 0xcd, 0xd6, 0x98, 0x05, 0x93, 0xcc, 0xef, 0x2a, 0x26, 0xb7, 0x99,
	0x34, 0x72, 0xbc, 0x0c, 0xd1, 0x93, 0xb1, 0xe9, 0x63, 0xdd, 0xc3, 0x63, 0x9b, 0x5b, 0x4c, 0x25,
	0xf8, 0x19, 0x3c, 0x37, 0xb5, 0xab, 0x62, 0x11, 0x29, 0x86, 0xd6, 0x61, 0xc5, 0x78, 0xad, 0x80,
	0x2b, 0xa0, 0x76, 0xba, 0x55, 0x6d, 0xcc, 0x1c, 0x4d, 0xc3, 0x94, 0x75, 0x16, 0xf7, 0x7e, 0xac,
	0x96, 0x3e, 0xff, 0xfe, 0x52, 0x07, 0x9e, 0xad, 0xc3, 0x35, 0x78, 0x41, 0x37, 0x7e, 0xaa, 0x19,
	0x3a, 0xe9, 0x43, 0xdf, 0x5a, 0xa2, 0x25, 0x58, 0xe6, 0xbe, 0xee, 0x7b, 0xd2, 0x2b, 0x73, 0x1f,
	0x6f, 0xc0, 0x8b, 0x39, 0xa5, 0xc5, 0x78, 0x00, 0x2b, 0xe6, 0x0c, 0x16, 0xe3, 0xc6, 0x1c, 0x0c,
	0xef, 0xe0, 0xcc, 0xa6, 0x89, 0x67, 0xcb, 0xf0, 0x3a, 0x74, 0x26, 0x7a, 0xab, 0x4e, 0xfa, 0xe8,
	0x55, 0xc4, 0x64, 0x46, 0x82, 0xe1, 0x19, 0x31, 0xfe, 0xdf, 0xf6, 0x7d, 0xc9, 0x94, 0x39, 0xeb,
	0xa2, 0x37, 0xb5, 0x87, 0x5f, 0xc0, 0x4b, 0x33, 0x3b, 0x58, 0xc2, 0x36, 0x3c, 0x65, 0xac, 0xc6,
	0xd5, 0x27, 0x8e, 0x83, 0x98, 0xd5, 0xe1, 0x15, 0x3b, 0xa9, 0x76, 0x18, 0x5a, 0x93, 0xec, 0x72,
	0x9e, 0xdb, 0xc9, 0x4c, 0x7e, 0xf9, 0x6f, 0xbe, 0xad, 0xb7, 0x0b, 0x70, 0x41, 0xb7, 0x47, 0xef,
	0x00, 0xac, 0x98, 0x9b, 0x44, 0x37, 0xe7, 0xb4, 0xc9, 0x47, 0xc7, 0xa9, 0x1f, 0x45, 0x6a, 0x70,
	0xf1, 0xf5, 0x37, 0xdf, 0x7e, 0x7d, 0x28, 0xaf, 0xa2, 0x2a, 0x29, 0x0a, 0x36, 0xfa, 0x04, 0x20,
	0x3c, 0x8c, 0x01, 0x5a, 0x2b, 0x72, 0xc8, 0x05, 0xcb, 0x69, 0x1c, 0x55, 0x6e, 0xa1, 0x6e, 0x69,
	0xa8, 0x3a, 0xaa, 0xcd, 0x81, 0x32, 0x83, 0xea, 0xf6, 0xd2, 0x2e, 0xf7, 0xc9, 0x0e, 0xf7, 0x77,
	0xd1, 0x57, 0x00, 0x97, 0xa6, 0x83, 0x80, 0x9a, 0xff, 0x36, 0xfd, 0x2b, 0x76, 0x4e, 0xeb, 0x38,
	0x25, 0x96, 0xf5, 0xbe, 0x66, 0xbd, 0x87, 0xee, 0x14, 0xb2, 0xaa, 0x31, 0xac, 0x8e, 0x2f, 0xd9,
	0x99, 0x4c, 0xf1, 0x2e, 0xfa, 0x08, 0x20, 0x3c, 0x8c, 0x51, 0xf1, 0x64, 0x73, 0x41, 0x2c, 0x9e,
	0x6c, 0x3e, 0x9d, 0xb8, 0xae, 0x69, 0xaf, 0x21, 0x3c, 0x87, 0x96, 0x86, 0xa1, 0x7d, 0x9c, 0x54,
	0xe7, 0xee, 0xde, 0xd0, 0x05, 0xfb, 0x43, 0x17, 0xfc, 0x1c, 0xba, 0xe0, 0xfd, 0xc8, 0x2d, 0xed,
	0x8f, 0xdc, 0xd2, 0xf7, 0x91, 0x5b, 0xda, 0xa8, 0x1e, 0x14, 0xbf, 0x9e, 0x2e, 0x4f, 0xd2, 0x98,
	0xa9, 0x5e, 0x45, 0xbf, 0x6b, 0xb7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x5d, 0xce, 0x64,
	0xd9, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ServerById items.
	ServerById(ctx context.Context, in *QueryServerByIdRequest, opts ...grpc.CallOption) (*QueryServerByIdResponse, error)
	// Queries a list of ServersByOwner items.
	ServersByOwner(ctx context.Context, in *QueryServersByOwnerRequest, opts ...grpc.CallOption) (*QueryServersByOwnerResponse, error)
	// Queries a list of AllServers items.
	AllServers(ctx context.Context, in *QueryAllServersRequest, opts ...grpc.CallOption) (*QueryAllServersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mcpchain.toolregistry.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ServerById(ctx context.Context, in *QueryServerByIdRequest, opts ...grpc.CallOption) (*QueryServerByIdResponse, error) {
	out := new(QueryServerByIdResponse)
	err := c.cc.Invoke(ctx, "/mcpchain.toolregistry.Query/ServerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ServersByOwner(ctx context.Context, in *QueryServersByOwnerRequest, opts ...grpc.CallOption) (*QueryServersByOwnerResponse, error) {
	out := new(QueryServersByOwnerResponse)
	err := c.cc.Invoke(ctx, "/mcpchain.toolregistry.Query/ServersByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllServers(ctx context.Context, in *QueryAllServersRequest, opts ...grpc.CallOption) (*QueryAllServersResponse, error) {
	out := new(QueryAllServersResponse)
	err := c.cc.Invoke(ctx, "/mcpchain.toolregistry.Query/AllServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ServerById items.
	ServerById(context.Context, *QueryServerByIdRequest) (*QueryServerByIdResponse, error)
	// Queries a list of ServersByOwner items.
	ServersByOwner(context.Context, *QueryServersByOwnerRequest) (*QueryServersByOwnerResponse, error)
	// Queries a list of AllServers items.
	AllServers(context.Context, *QueryAllServersRequest) (*QueryAllServersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ServerById(ctx context.Context, req *QueryServerByIdRequest) (*QueryServerByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerById not implemented")
}
func (*UnimplementedQueryServer) ServersByOwner(ctx context.Context, req *QueryServersByOwnerRequest) (*QueryServersByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServersByOwner not implemented")
}
func (*UnimplementedQueryServer) AllServers(ctx context.Context, req *QueryAllServersRequest) (*QueryAllServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllServers not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcpchain.toolregistry.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ServerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryServerByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ServerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcpchain.toolregistry.Query/ServerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ServerById(ctx, req.(*QueryServerByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ServersByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryServersByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ServersByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcpchain.toolregistry.Query/ServersByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ServersByOwner(ctx, req.(*QueryServersByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcpchain.toolregistry.Query/AllServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllServers(ctx, req.(*QueryAllServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mcpchain.toolregistry.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ServerById",
			Handler:    _Query_ServerById_Handler,
		},
		{
			MethodName: "ServersByOwner",
			Handler:    _Query_ServersByOwner_Handler,
		},
		{
			MethodName: "AllServers",
			Handler:    _Query_AllServers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcpchain/toolregistry/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryServerByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryServerByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryServerByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryServerByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryServerByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryServerByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Server != nil {
		{
			size, err := m.Server.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryServersByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryServersByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryServersByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryServersByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryServersByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryServersByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Servers) > 0 {
		for iNdEx := len(m.Servers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Servers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllServersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllServersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllServersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllServersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllServersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllServersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Servers) > 0 {
		for iNdEx := len(m.Servers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Servers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryServerByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryServerByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Server != nil {
		l = m.Server.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryServersByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryServersByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Servers) > 0 {
		for _, e := range m.Servers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAllServersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllServersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Servers) > 0 {
		for _, e := range m.Servers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryServerByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryServerByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryServerByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryServerByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryServerByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryServerByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Server", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Server == nil {
				m.Server = &RegisteredServer{}
			}
			if err := m.Server.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryServersByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryServersByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryServersByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryServersByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryServersByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryServersByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Servers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Servers = append(m.Servers, &RegisteredServer{})
			if err := m.Servers[len(m.Servers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllServersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllServersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllServersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllServersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllServersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllServersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Servers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Servers = append(m.Servers, &RegisteredServer{})
			if err := m.Servers[len(m.Servers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
