// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package attestation

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_AttestationRecord                protoreflect.MessageDescriptor
	fd_AttestationRecord_interaction_id protoreflect.FieldDescriptor
	fd_AttestationRecord_agent_id       protoreflect.FieldDescriptor
	fd_AttestationRecord_tool_id        protoreflect.FieldDescriptor
	fd_AttestationRecord_tool_name      protoreflect.FieldDescriptor
	fd_AttestationRecord_request_hash   protoreflect.FieldDescriptor
	fd_AttestationRecord_response_hash  protoreflect.FieldDescriptor
	fd_AttestationRecord_timestamp      protoreflect.FieldDescriptor
)

func init() {
	file_mcpchain_attestation_attestation_record_proto_init()
	md_AttestationRecord = File_mcpchain_attestation_attestation_record_proto.Messages().ByName("AttestationRecord")
	fd_AttestationRecord_interaction_id = md_AttestationRecord.Fields().ByName("interaction_id")
	fd_AttestationRecord_agent_id = md_AttestationRecord.Fields().ByName("agent_id")
	fd_AttestationRecord_tool_id = md_AttestationRecord.Fields().ByName("tool_id")
	fd_AttestationRecord_tool_name = md_AttestationRecord.Fields().ByName("tool_name")
	fd_AttestationRecord_request_hash = md_AttestationRecord.Fields().ByName("request_hash")
	fd_AttestationRecord_response_hash = md_AttestationRecord.Fields().ByName("response_hash")
	fd_AttestationRecord_timestamp = md_AttestationRecord.Fields().ByName("timestamp")
}

var _ protoreflect.Message = (*fastReflection_AttestationRecord)(nil)

type fastReflection_AttestationRecord AttestationRecord

func (x *AttestationRecord) ProtoReflect() protoreflect.Message {
	return (*fastReflection_AttestationRecord)(x)
}

func (x *AttestationRecord) slowProtoReflect() protoreflect.Message {
	mi := &file_mcpchain_attestation_attestation_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_AttestationRecord_messageType fastReflection_AttestationRecord_messageType
var _ protoreflect.MessageType = fastReflection_AttestationRecord_messageType{}

type fastReflection_AttestationRecord_messageType struct{}

func (x fastReflection_AttestationRecord_messageType) Zero() protoreflect.Message {
	return (*fastReflection_AttestationRecord)(nil)
}
func (x fastReflection_AttestationRecord_messageType) New() protoreflect.Message {
	return new(fastReflection_AttestationRecord)
}
func (x fastReflection_AttestationRecord_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_AttestationRecord
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_AttestationRecord) Descriptor() protoreflect.MessageDescriptor {
	return md_AttestationRecord
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_AttestationRecord) Type() protoreflect.MessageType {
	return _fastReflection_AttestationRecord_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_AttestationRecord) New() protoreflect.Message {
	return new(fastReflection_AttestationRecord)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_AttestationRecord) Interface() protoreflect.ProtoMessage {
	return (*AttestationRecord)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_AttestationRecord) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.InteractionId != "" {
		value := protoreflect.ValueOfString(x.InteractionId)
		if !f(fd_AttestationRecord_interaction_id, value) {
			return
		}
	}
	if x.AgentId != "" {
		value := protoreflect.ValueOfString(x.AgentId)
		if !f(fd_AttestationRecord_agent_id, value) {
			return
		}
	}
	if x.ToolId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ToolId)
		if !f(fd_AttestationRecord_tool_id, value) {
			return
		}
	}
	if x.ToolName != "" {
		value := protoreflect.ValueOfString(x.ToolName)
		if !f(fd_AttestationRecord_tool_name, value) {
			return
		}
	}
	if x.RequestHash != "" {
		value := protoreflect.ValueOfString(x.RequestHash)
		if !f(fd_AttestationRecord_request_hash, value) {
			return
		}
	}
	if x.ResponseHash != "" {
		value := protoreflect.ValueOfString(x.ResponseHash)
		if !f(fd_AttestationRecord_response_hash, value) {
			return
		}
	}
	if x.Timestamp != int64(0) {
		value := protoreflect.ValueOfInt64(x.Timestamp)
		if !f(fd_AttestationRecord_timestamp, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_AttestationRecord) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "mcpchain.attestation.AttestationRecord.interaction_id":
		return x.InteractionId != ""
	case "mcpchain.attestation.AttestationRecord.agent_id":
		return x.AgentId != ""
	case "mcpchain.attestation.AttestationRecord.tool_id":
		return x.ToolId != uint64(0)
	case "mcpchain.attestation.AttestationRecord.tool_name":
		return x.ToolName != ""
	case "mcpchain.attestation.AttestationRecord.request_hash":
		return x.RequestHash != ""
	case "mcpchain.attestation.AttestationRecord.response_hash":
		return x.ResponseHash != ""
	case "mcpchain.attestation.AttestationRecord.timestamp":
		return x.Timestamp != int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mcpchain.attestation.AttestationRecord"))
		}
		panic(fmt.Errorf("message mcpchain.attestation.AttestationRecord does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AttestationRecord) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "mcpchain.attestation.AttestationRecord.interaction_id":
		x.InteractionId = ""
	case "mcpchain.attestation.AttestationRecord.agent_id":
		x.AgentId = ""
	case "mcpchain.attestation.AttestationRecord.tool_id":
		x.ToolId = uint64(0)
	case "mcpchain.attestation.AttestationRecord.tool_name":
		x.ToolName = ""
	case "mcpchain.attestation.AttestationRecord.request_hash":
		x.RequestHash = ""
	case "mcpchain.attestation.AttestationRecord.response_hash":
		x.ResponseHash = ""
	case "mcpchain.attestation.AttestationRecord.timestamp":
		x.Timestamp = int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mcpchain.attestation.AttestationRecord"))
		}
		panic(fmt.Errorf("message mcpchain.attestation.AttestationRecord does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_AttestationRecord) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "mcpchain.attestation.AttestationRecord.interaction_id":
		value := x.InteractionId
		return protoreflect.ValueOfString(value)
	case "mcpchain.attestation.AttestationRecord.agent_id":
		value := x.AgentId
		return protoreflect.ValueOfString(value)
	case "mcpchain.attestation.AttestationRecord.tool_id":
		value := x.ToolId
		return protoreflect.ValueOfUint64(value)
	case "mcpchain.attestation.AttestationRecord.tool_name":
		value := x.ToolName
		return protoreflect.ValueOfString(value)
	case "mcpchain.attestation.AttestationRecord.request_hash":
		value := x.RequestHash
		return protoreflect.ValueOfString(value)
	case "mcpchain.attestation.AttestationRecord.response_hash":
		value := x.ResponseHash
		return protoreflect.ValueOfString(value)
	case "mcpchain.attestation.AttestationRecord.timestamp":
		value := x.Timestamp
		return protoreflect.ValueOfInt64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mcpchain.attestation.AttestationRecord"))
		}
		panic(fmt.Errorf("message mcpchain.attestation.AttestationRecord does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AttestationRecord) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "mcpchain.attestation.AttestationRecord.interaction_id":
		x.InteractionId = value.Interface().(string)
	case "mcpchain.attestation.AttestationRecord.agent_id":
		x.AgentId = value.Interface().(string)
	case "mcpchain.attestation.AttestationRecord.tool_id":
		x.ToolId = value.Uint()
	case "mcpchain.attestation.AttestationRecord.tool_name":
		x.ToolName = value.Interface().(string)
	case "mcpchain.attestation.AttestationRecord.request_hash":
		x.RequestHash = value.Interface().(string)
	case "mcpchain.attestation.AttestationRecord.response_hash":
		x.ResponseHash = value.Interface().(string)
	case "mcpchain.attestation.AttestationRecord.timestamp":
		x.Timestamp = value.Int()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mcpchain.attestation.AttestationRecord"))
		}
		panic(fmt.Errorf("message mcpchain.attestation.AttestationRecord does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AttestationRecord) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "mcpchain.attestation.AttestationRecord.interaction_id":
		panic(fmt.Errorf("field interaction_id of message mcpchain.attestation.AttestationRecord is not mutable"))
	case "mcpchain.attestation.AttestationRecord.agent_id":
		panic(fmt.Errorf("field agent_id of message mcpchain.attestation.AttestationRecord is not mutable"))
	case "mcpchain.attestation.AttestationRecord.tool_id":
		panic(fmt.Errorf("field tool_id of message mcpchain.attestation.AttestationRecord is not mutable"))
	case "mcpchain.attestation.AttestationRecord.tool_name":
		panic(fmt.Errorf("field tool_name of message mcpchain.attestation.AttestationRecord is not mutable"))
	case "mcpchain.attestation.AttestationRecord.request_hash":
		panic(fmt.Errorf("field request_hash of message mcpchain.attestation.AttestationRecord is not mutable"))
	case "mcpchain.attestation.AttestationRecord.response_hash":
		panic(fmt.Errorf("field response_hash of message mcpchain.attestation.AttestationRecord is not mutable"))
	case "mcpchain.attestation.AttestationRecord.timestamp":
		panic(fmt.Errorf("field timestamp of message mcpchain.attestation.AttestationRecord is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mcpchain.attestation.AttestationRecord"))
		}
		panic(fmt.Errorf("message mcpchain.attestation.AttestationRecord does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_AttestationRecord) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "mcpchain.attestation.AttestationRecord.interaction_id":
		return protoreflect.ValueOfString("")
	case "mcpchain.attestation.AttestationRecord.agent_id":
		return protoreflect.ValueOfString("")
	case "mcpchain.attestation.AttestationRecord.tool_id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "mcpchain.attestation.AttestationRecord.tool_name":
		return protoreflect.ValueOfString("")
	case "mcpchain.attestation.AttestationRecord.request_hash":
		return protoreflect.ValueOfString("")
	case "mcpchain.attestation.AttestationRecord.response_hash":
		return protoreflect.ValueOfString("")
	case "mcpchain.attestation.AttestationRecord.timestamp":
		return protoreflect.ValueOfInt64(int64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mcpchain.attestation.AttestationRecord"))
		}
		panic(fmt.Errorf("message mcpchain.attestation.AttestationRecord does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_AttestationRecord) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in mcpchain.attestation.AttestationRecord", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_AttestationRecord) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AttestationRecord) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_AttestationRecord) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_AttestationRecord) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*AttestationRecord)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.InteractionId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AgentId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.ToolId != 0 {
			n += 1 + runtime.Sov(uint64(x.ToolId))
		}
		l = len(x.ToolName)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.RequestHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ResponseHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Timestamp != 0 {
			n += 1 + runtime.Sov(uint64(x.Timestamp))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*AttestationRecord)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Timestamp != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Timestamp))
			i--
			dAtA[i] = 0x38
		}
		if len(x.ResponseHash) > 0 {
			i -= len(x.ResponseHash)
			copy(dAtA[i:], x.ResponseHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ResponseHash)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.RequestHash) > 0 {
			i -= len(x.RequestHash)
			copy(dAtA[i:], x.RequestHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.RequestHash)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.ToolName) > 0 {
			i -= len(x.ToolName)
			copy(dAtA[i:], x.ToolName)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ToolName)))
			i--
			dAtA[i] = 0x22
		}
		if x.ToolId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ToolId))
			i--
			dAtA[i] = 0x18
		}
		if len(x.AgentId) > 0 {
			i -= len(x.AgentId)
			copy(dAtA[i:], x.AgentId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AgentId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.InteractionId) > 0 {
			i -= len(x.InteractionId)
			copy(dAtA[i:], x.InteractionId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.InteractionId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*AttestationRecord)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AttestationRecord: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AttestationRecord: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InteractionId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.InteractionId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AgentId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ToolId", wireType)
				}
				x.ToolId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ToolId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ToolName", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ToolName = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RequestHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.RequestHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ResponseHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ResponseHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
				}
				x.Timestamp = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Timestamp |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: mcpchain/attestation/attestation_record.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestationRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InteractionId string `protobuf:"bytes,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	AgentId       string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ToolId        uint64 `protobuf:"varint,3,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolName      string `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	RequestHash   string `protobuf:"bytes,5,opt,name=request_hash,json=requestHash,proto3" json:"request_hash,omitempty"`
	ResponseHash  string `protobuf:"bytes,6,opt,name=response_hash,json=responseHash,proto3" json:"response_hash,omitempty"`
	Timestamp     int64  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *AttestationRecord) Reset() {
	*x = AttestationRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcpchain_attestation_attestation_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttestationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRecord) ProtoMessage() {}

// Deprecated: Use AttestationRecord.ProtoReflect.Descriptor instead.
func (*AttestationRecord) Descriptor() ([]byte, []int) {
	return file_mcpchain_attestation_attestation_record_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationRecord) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *AttestationRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AttestationRecord) GetToolId() uint64 {
	if x != nil {
		return x.ToolId
	}
	return 0
}

func (x *AttestationRecord) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AttestationRecord) GetRequestHash() string {
	if x != nil {
		return x.RequestHash
	}
	return ""
}

func (x *AttestationRecord) GetResponseHash() string {
	if x != nil {
		return x.ResponseHash
	}
	return ""
}

func (x *AttestationRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_mcpchain_attestation_attestation_record_proto protoreflect.FileDescriptor

var file_mcpchain_attestation_attestation_record_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6d, 0x63, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x14, 0x6d, 0x63, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xf1, 0x01, 0x0a, 0x11, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x74, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6f, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0xc6, 0x01, 0x0a, 0x18, 0x63, 0x6f,
	0x6d, 0x2e, 0x6d, 0x63, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x61, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x16, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x21, 0x6d, 0x63, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d,
	0x63, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0xa2, 0x02, 0x03, 0x4d, 0x41, 0x58, 0xaa, 0x02, 0x14, 0x4d, 0x63, 0x70, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0xca, 0x02, 0x14, 0x4d, 0x63, 0x70, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x41, 0x74, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0xe2, 0x02, 0x20, 0x4d, 0x63, 0x70, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5c, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x15, 0x4d, 0x63, 0x70,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mcpchain_attestation_attestation_record_proto_rawDescOnce sync.Once
	file_mcpchain_attestation_attestation_record_proto_rawDescData = file_mcpchain_attestation_attestation_record_proto_rawDesc
)

func file_mcpchain_attestation_attestation_record_proto_rawDescGZIP() []byte {
	file_mcpchain_attestation_attestation_record_proto_rawDescOnce.Do(func() {
		file_mcpchain_attestation_attestation_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcpchain_attestation_attestation_record_proto_rawDescData)
	})
	return file_mcpchain_attestation_attestation_record_proto_rawDescData
}

var file_mcpchain_attestation_attestation_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcpchain_attestation_attestation_record_proto_goTypes = []interface{}{
	(*AttestationRecord)(nil), // 0: mcpchain.attestation.AttestationRecord
}
var file_mcpchain_attestation_attestation_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcpchain_attestation_attestation_record_proto_init() }
func file_mcpchain_attestation_attestation_record_proto_init() {
	if File_mcpchain_attestation_attestation_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mcpchain_attestation_attestation_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttestationRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcpchain_attestation_attestation_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcpchain_attestation_attestation_record_proto_goTypes,
		DependencyIndexes: file_mcpchain_attestation_attestation_record_proto_depIdxs,
		MessageInfos:      file_mcpchain_attestation_attestation_record_proto_msgTypes,
	}.Build()
	File_mcpchain_attestation_attestation_record_proto = out.File
	file_mcpchain_attestation_attestation_record_proto_rawDesc = nil
	file_mcpchain_attestation_attestation_record_proto_goTypes = nil
	file_mcpchain_attestation_attestation_record_proto_depIdxs = nil
}
